### ISSUE TITLE
!m People -> You're doing good work People!

### ISSUE THREAD

**Issue by bruceadams** [LindseyB/XOmBot#10]
#### Feature request

Teach XOmBot about "!m". In an IRC chat, if someone says: "!m name", XOmBot should respond with "You're doing good work, name!" Where "name" can be anything.

I'll look at adding this myself... not quite sure when I'll find time.

**Comment by bruceadams** [comment]
Some background here: http://bangmotivate.appspot.com/

**Comment by LindseyB** [comment]
Closed in #12
